// <auto-generated />
using System;
using Beca.ViviendaInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beca.ViviendaInfo.API.Migrations
{
    [DbContext(typeof(ViviendaInfoContext))]
    [Migration("20221104080027_ViviendaInfoDBInitialMigration")]
    partial class ViviendaInfoDBInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Beca.ViviendaInfo.API.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViviendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ViviendaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Beca.ViviendaInfo.API.Entities.Vivienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Propietario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Viviendas");
                });

            modelBuilder.Entity("Beca.ViviendaInfo.API.Entities.Reserva", b =>
                {
                    b.HasOne("Beca.ViviendaInfo.API.Entities.Vivienda", "Vivienda")
                        .WithMany("Reservas")
                        .HasForeignKey("ViviendaId");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Beca.ViviendaInfo.API.Entities.Vivienda", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
